export { default as Authors } from './Authors';
export { default as AuthorEdit } from './AuthorEdit';
export { default as Categories } from './Categories';
export { default as Posts } from './post/Posts';
export { default as Edit } from './post/Edit';
export { default as Tags } from './Tags';
export { default as Comments } from './Comments';
export { default as AdminHome } from './Home';
export { default as AdminLayout } from './Layout';